-- ════════════════════════════════════════════════════════════════════════════
-- BILLING OVERHAUL MIGRATION
-- Generated by hand on 2026-04-16 (NOT via prisma migrate dev — see note below).
-- ════════════════════════════════════════════════════════════════════════════
--
-- WHY HAND-WRITTEN:
-- prisma migrate dev would attempt to DROP transcripts.embedding (vector(1536))
-- and transcripts.search_text because those columns are managed via raw SQL
-- and not represented in schema.prisma. Hand-writing this migration preserves
-- those columns and adds custom logic Prisma cannot generate (yearly invoice
-- number sequence, snapshot field backfill, BILLED enum data migration).
--
-- TO APPLY:
--   psql $DATABASE_URL -f prisma/migrations/20260416_billing_overhaul/migration.sql
--   then mark as applied:
--   npx prisma migrate resolve --applied 20260416_billing_overhaul
--
-- TO ROLLBACK: see rollback.sql in this directory.
-- ════════════════════════════════════════════════════════════════════════════

BEGIN;

-- ─── 1. ENUM CHANGES ───────────────────────────────────────────────────────

-- Add CUSTOM_DAYS to BillingCadence (additive, safe)
ALTER TYPE "BillingCadence" ADD VALUE IF NOT EXISTS 'CUSTOM_DAYS';

-- Drop SessionStatus.BILLED (after data migration).
-- Step 1: migrate any sessions with status='BILLED' to status='ARCHIVED'.
-- The TimeEntry.status field is the authoritative billing state; Session.BILLED
-- was a duplicated-state remnant.
UPDATE sessions SET status = 'ARCHIVED' WHERE status = 'BILLED';

-- Step 2: rebuild the enum without BILLED. Postgres requires a swap because
-- ALTER TYPE ... DROP VALUE is not supported.
ALTER TYPE "SessionStatus" RENAME TO "SessionStatus_old";
CREATE TYPE "SessionStatus" AS ENUM ('CAPTURED', 'REVIEWED', 'ARCHIVED');
ALTER TABLE sessions
  ALTER COLUMN status DROP DEFAULT,
  ALTER COLUMN status TYPE "SessionStatus" USING status::text::"SessionStatus",
  ALTER COLUMN status SET DEFAULT 'CAPTURED';
DROP TYPE "SessionStatus_old";

-- ─── 2. CLIENT TABLE ADDITIONS ─────────────────────────────────────────────

ALTER TABLE clients
  ADD COLUMN "displayName"          TEXT,
  ADD COLUMN "customCadenceDays"    INTEGER,
  ADD COLUMN "billingContactName"   TEXT,
  ADD COLUMN "billingContactEmail"  TEXT,
  ADD COLUMN "billingPausedUntil"   TIMESTAMP(3),
  ADD COLUMN "billingNotes"         TEXT,
  ADD COLUMN "nextInvoiceDueAt"     TIMESTAMP(3),
  ADD COLUMN "billingTimezone"      TEXT,
  ADD COLUMN "retainer"             DECIMAL(10,2) NOT NULL DEFAULT 0;

CREATE INDEX "clients_nextInvoiceDueAt_idx" ON clients("nextInvoiceDueAt");

-- Validate customCadenceDays range when present
ALTER TABLE clients
  ADD CONSTRAINT clients_customCadenceDays_range
  CHECK ("customCadenceDays" IS NULL OR ("customCadenceDays" >= 1 AND "customCadenceDays" <= 365));

-- ─── 3. COACH SETTINGS ADDITIONS + REMOVAL ─────────────────────────────────

ALTER TABLE coach_settings
  ADD COLUMN "defaultBillingDayOfMonth" INTEGER,
  ADD COLUMN "autoApproveUnderCents"    INTEGER,
  ADD COLUMN "invoicePrefix"            TEXT NOT NULL DEFAULT 'CIQ',
  ADD COLUMN "invoiceNumberPadding"     INTEGER NOT NULL DEFAULT 4,
  ADD COLUMN "timezone"                 TEXT NOT NULL DEFAULT 'America/Chicago';

-- Validate defaultBillingDayOfMonth range (1-28 to avoid month-edge issues;
-- end-of-month clamp logic in code handles the 29-31 case)
ALTER TABLE coach_settings
  ADD CONSTRAINT coach_settings_defaultBillingDayOfMonth_range
  CHECK ("defaultBillingDayOfMonth" IS NULL OR ("defaultBillingDayOfMonth" >= 1 AND "defaultBillingDayOfMonth" <= 28));

-- Drop the unused billingDayOfWeek column.
-- Pre-migration check showed 1 non-null value; semantically replaced by
-- defaultBillingDayOfMonth (different concept, no auto-translation possible).
ALTER TABLE coach_settings DROP COLUMN "billingDayOfWeek";

-- ─── 4. INVOICE TABLE ADDITIONS ────────────────────────────────────────────

ALTER TABLE invoices
  ADD COLUMN "snapshotClientName"      TEXT,
  ADD COLUMN "snapshotBillingEmail"    TEXT,
  ADD COLUMN "snapshotBillingCcEmails" TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN "snapshotHourlyRate"      DECIMAL(10,2),
  ADD COLUMN "parentInvoiceId"         UUID,
  ADD COLUMN "lastReminderSentAt"      TIMESTAMP(3);

-- Backfill snapshot fields for existing invoices from current client values.
-- Best-effort: existing SENT/PAID invoices will reflect CURRENT client data,
-- which may differ from what was actually sent. Acceptable: no historical
-- snapshot exists, this is the closest we can get.
UPDATE invoices i
SET
  "snapshotClientName"      = c.name,
  "snapshotBillingEmail"    = c.email,
  "snapshotBillingCcEmails" = c."secondaryEmails",
  "snapshotHourlyRate"      = c."hourlyRate"
FROM clients c
WHERE i."clientId" = c.id;

-- After backfill, snapshot fields stay nullable to allow legacy rows that
-- might exist before this migration ran. New invoices created post-migration
-- MUST populate these (enforced in application code, not DB).

-- ─── 5. NEW TABLE: invoice_adjustments ─────────────────────────────────────

CREATE TABLE invoice_adjustments (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "invoiceId" UUID NOT NULL,
  kind        TEXT NOT NULL,
  amount      DECIMAL(10,2) NOT NULL,
  description TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT invoice_adjustments_invoiceId_fkey
    FOREIGN KEY ("invoiceId") REFERENCES invoices(id) ON DELETE CASCADE,
  CONSTRAINT invoice_adjustments_kind_check
    CHECK (kind IN ('credit', 'discount', 'expense'))
);
CREATE INDEX invoice_adjustments_invoiceId_idx ON invoice_adjustments("invoiceId");

-- ─── 6. NEW TABLE: billing_audit_logs ──────────────────────────────────────

CREATE TABLE billing_audit_logs (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event       TEXT NOT NULL,
  actor       TEXT,
  "clientId"  UUID,
  "invoiceId" UUID,
  payload     JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX billing_audit_logs_clientId_createdAt_idx
  ON billing_audit_logs("clientId", "createdAt" DESC);
CREATE INDEX billing_audit_logs_invoiceId_idx
  ON billing_audit_logs("invoiceId");
CREATE INDEX billing_audit_logs_event_createdAt_idx
  ON billing_audit_logs(event, "createdAt" DESC);

-- ─── 7. INVOICE NUMBER SEQUENCE ────────────────────────────────────────────

-- Per-year sequence allocated atomically inside the same transaction as the
-- invoice insert. Replaces the read-then-write pattern in
-- src/app/api/invoices/generate/route.ts:59-66 that races under concurrent load.

-- Helper function: ensures a sequence exists for the given year. Cron calls
-- this at the top of each run; idempotent.
CREATE OR REPLACE FUNCTION ensure_invoice_seq_for_year(y INTEGER)
RETURNS VOID AS $$
BEGIN
  EXECUTE format('CREATE SEQUENCE IF NOT EXISTS invoice_number_seq_%s START 1', y);
END $$ LANGUAGE plpgsql;

-- Create the current year's sequence and set it past existing invoice numbers
-- so we don't collide with already-issued numbers.
SELECT ensure_invoice_seq_for_year(EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER);

DO $$
DECLARE
  y INTEGER := EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER;
  max_seq INTEGER;
BEGIN
  -- Find the highest existing invoice number for this year, if any.
  -- Pattern: {prefix}-{year}-{padded_seq}
  SELECT COALESCE(MAX(SPLIT_PART("invoiceNumber", '-', 3)::INTEGER), 0)
  INTO max_seq
  FROM invoices
  WHERE "invoiceNumber" LIKE '%-' || y || '-%';

  IF max_seq > 0 THEN
    EXECUTE format('SELECT setval(''invoice_number_seq_%s'', %s)', y, max_seq);
  END IF;
END $$;

-- ─── 8. NOTES FOR DEVS ─────────────────────────────────────────────────────
-- - Snapshot fields backfilled best-effort from current client values.
-- - Future: a follow-up migration could enforce NOT NULL on snapshot fields
--   once we trust all new invoices populate them at draft creation.
-- - The pgvector embedding columns (transcripts.embedding, transcripts.search_text)
--   are intentionally NOT touched by this migration — they're managed via raw SQL
--   outside Prisma. See schema.prisma:166-167.
-- - Dropping SessionStatus.BILLED is irreversible. If you ever need it back,
--   add a new ARCHIVED_BILLED variant — don't bring BILLED back.

COMMIT;
