-- ════════════════════════════════════════════════════════════════════════════
-- BILLING GROUPS MIGRATION
-- Generated by hand on 2026-05-01 (NOT via prisma migrate dev — see note below).
-- ════════════════════════════════════════════════════════════════════════════
--
-- WHY HAND-WRITTEN:
-- prisma migrate dev would attempt to DROP transcripts.embedding (vector(1536))
-- and transcripts.search_text because those columns are managed via raw SQL
-- and not represented in schema.prisma. Hand-writing this migration preserves
-- those columns. It also adds the invoice_billable_xor CHECK constraint that
-- Prisma cannot express directly.
--
-- WHAT THIS DOES:
--   1. Creates billing_groups table
--   2. Adds clients.billing_group_id (nullable FK)
--   3. Makes invoices.client_id nullable, adds invoices.group_id
--   4. Adds CHECK constraint: exactly one of client_id / group_id must be set
--   5. Adds billing_audit_logs.group_id
--
-- TO APPLY:
--   psql $DATABASE_URL -f prisma/migrations/20260501_billing_groups/migration.sql
--   then mark as applied:
--   npx prisma migrate resolve --applied 20260501_billing_groups
--
-- TO ROLLBACK: see rollback.sql in this directory.
-- ════════════════════════════════════════════════════════════════════════════

BEGIN;

-- ─── 1. BILLING_GROUPS TABLE ───────────────────────────────────────────────

CREATE TABLE "billing_groups" (
  "id"                    UUID            NOT NULL DEFAULT gen_random_uuid(),
  "name"                  TEXT            NOT NULL,
  "displayName"           TEXT,
  "billingContactName"    TEXT,
  "billingContactEmail"   TEXT            NOT NULL,
  "ccEmails"              TEXT[]          NOT NULL DEFAULT ARRAY[]::TEXT[],
  "address"               JSONB,
  "hourlyRate"            DECIMAL(10, 2),
  "billingCadence"        "BillingCadence" NOT NULL DEFAULT 'MONTHLY',
  "customCadenceDays"     INTEGER,
  "billingPausedUntil"    TIMESTAMP(3),
  "nextInvoiceDueAt"      TIMESTAMP(3),
  "billingTimezone"       TEXT,
  "retainer"              DECIMAL(10, 2)  NOT NULL DEFAULT 0,
  "stripeCustomerId"      TEXT,
  "status"                "ClientStatus"  NOT NULL DEFAULT 'ACTIVE',
  "notes"                 TEXT,
  "tags"                  TEXT[]          NOT NULL DEFAULT ARRAY[]::TEXT[],
  "createdAt"             TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"             TIMESTAMP(3)    NOT NULL,
  CONSTRAINT "billing_groups_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "billing_groups_status_idx"           ON "billing_groups"("status");
CREATE INDEX "billing_groups_nextInvoiceDueAt_idx" ON "billing_groups"("nextInvoiceDueAt");

-- ─── 2. CLIENTS.billing_group_id ───────────────────────────────────────────

ALTER TABLE "clients"
  ADD COLUMN "billingGroupId" UUID;

CREATE INDEX "clients_billingGroupId_idx" ON "clients"("billingGroupId");

ALTER TABLE "clients"
  ADD CONSTRAINT "clients_billingGroupId_fkey"
  FOREIGN KEY ("billingGroupId") REFERENCES "billing_groups"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

-- ─── 3. INVOICES: clientId nullable + groupId column ───────────────────────

ALTER TABLE "invoices"
  ALTER COLUMN "clientId" DROP NOT NULL;

ALTER TABLE "invoices"
  ADD COLUMN "groupId" UUID;

CREATE INDEX "invoices_groupId_idx" ON "invoices"("groupId");

ALTER TABLE "invoices"
  ADD CONSTRAINT "invoices_groupId_fkey"
  FOREIGN KEY ("groupId") REFERENCES "billing_groups"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

-- Exactly one of clientId / groupId must be set.
-- (clientId IS NOT NULL)::int + (groupId IS NOT NULL)::int = 1
ALTER TABLE "invoices"
  ADD CONSTRAINT "invoice_billable_xor"
  CHECK (
    (("clientId" IS NOT NULL)::int + ("groupId" IS NOT NULL)::int) = 1
  );

-- ─── 4. BILLING_AUDIT_LOGS.group_id ────────────────────────────────────────

ALTER TABLE "billing_audit_logs"
  ADD COLUMN "groupId" UUID;

CREATE INDEX "billing_audit_logs_groupId_createdAt_idx"
  ON "billing_audit_logs"("groupId", "createdAt" DESC);

COMMIT;
